### ISSUE TITLE
Issue creating spending bundle

### ISSUE THREAD

**Issue by chiaslimes** [Chia-Network/chia-nft-minting-tool#11]
Hi there! I'm getting the following when trying to create spending bundles - any insight?

`chianft create-mint-spend-bundles -w 2 -a txch14tfczs0zfgs48r4yl03zeypkcalt5s9pk7sy2c8c4hlwcjmlyafq3ef9xg -r 575 -t True test.csv output.pkl`

```
Traceback (most recent call last):
  File "/home/chiaslime/chia-nft-minting-tool/venv/bin/chianft", line 33, in <module>
    sys.exit(load_entry_point('chianft', 'console_scripts', 'chianft')())
  File "/home/chiaslime/chia-nft-minting-tool/chianft/cmds/cli.py", line 231, in main
    asyncio.run(cli())  # pylint: disable=no-value-for-parameter
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/chiaslime/chia-nft-minting-tool/chianft/cmds/cli.py", line 151, in create_spend_bundles_cmd
    asyncio.get_event_loop().run_until_complete(do_command())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/chiaslime/chia-nft-minting-tool/chianft/cmds/cli.py", line 132, in do_command
    spend_bundles = await minter.create_spend_bundles(
  File "/home/chiaslime/chia-nft-minting-tool/chianft/util/mint.py", line 137, in create_spend_bundles
    resp = await self.wallet_client.nft_mint_bulk(
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/chia/rpc/wallet_rpc_client.py", line 802, in nft_mint_bulk
    response = await self.fetch("nft_mint_bulk", request)
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/chia/rpc/rpc_client.py", line 46, in fetch
    response.raise_for_status()
  File "/home/chiaslime/chia-nft-minting-tool/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://localhost:9256/nft_mint_bulk')
```

**Comment by chiaslimes** [comment]
Yep, wallet was running and sync'd.  Was on 1.6.

**Comment by MumfMeisterT** [comment]
160 doesn't have the nft_mint_bulk endpoint, if you upgrade to 170 this issue should resolve.
